# Generated by Django 2.2.6 on 2021-08-24 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('', 'Blank'), ('A', 'Name A'), ('B', 'Name B'), ('C', 'Name C')], default='', max_length=1)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('A', 'Status A'), ('B', 'Status B'), ('C', 'Status C')], default='A', max_length=1)),
                ('latitude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_latitude', to=settings.AUTH_USER_MODEL)),
                ('longitude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_longitude', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
