# Generated by Django 2.2.6 on 2021-08-24 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='last_active',
        ),
        migrations.RemoveField(
            model_name='object',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='object',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='object',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='object',
            name='status',
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('A', 'Status A'), ('B', 'Status B'), ('C', 'Status C')], default='A', max_length=1)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.Object')),
            ],
        ),
    ]
