# Generated by Django 2.2.6 on 2021-08-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0002_auto_20210824_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='message',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
