# Generated by Django 2.2.6 on 2021-10-27 04:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcode',
            name='zip_code',
            field=models.PositiveIntegerField(default=0, unique=True, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(0)]),
        ),
    ]
